# New ports collection makefile for:   odbcshell
# Date created:        31 March 2001
# Whom:                David M. Syzdek <syzdek@bindlebinaries.com>
#
# $FreeBSD$
#

PORTNAME=      odbcshell
PORTVERSION=   0.0.223.g8c55b2b
CATEGORIES=    databases
MASTER_SITES=  http://scm.bindlebinaries.com/pub/software/odbcshell/

MAINTAINER=    syzdek@bindlebinaries.com
COMMENT=       ODBC command line client and script interpreter.

RUN_DEPENDS=   
LIB_DEPENDS=   

GNU_CONFIGURE= yes
USE_GMAKE=     yes

PLIST_FILES=   bin/odbcshell

.include <bsd.port.mk>
